# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  # Categories: /categories
  # Tags: /tags

# stylesheets loaded in the <head>
stylesheets:
  - /css/joker.css

# scripts loaded in the end of the body
scripts:
  - /js/utils.js
  - /js/event.js
  - /js/joker.js

cdn:
  css:
    fontawesome: https://cdn.bootcdn.net/ajax/libs/font-awesome/4.7.0/css/font-awesome.css
    cc:
  js:
    jqury: https://code.jquery.com/jquery-3.3.1.slim.min.js

logo:
  imgurl: /img/logo.png

# 主题
highlight_theme: default

# favicon
favicon: /favicon.ico

# 社交图标

social_icon:
  twitter: xx
  github: xx
  weibo: xx
  weixin: xx
  qq: xx

site-info:
  desc: noe
  keywords: noe
  author: noe
  copyright: noe

# 多用于about页面
authorInfo:
  avatar:
  selfIntro: 何海洋，1998，男。一名坚定的共产主义拥护者。2020年毕业于中国石油大学（华东）软件工程专业。对于软件工程开发有极高的自我认知，精通Java、JavaScript、C++等多门编程语言。喜欢研究编译原理、计算机网络等方便的编程技巧。同时也是多项开源社区的核心代码的领导者和布道者。
  # 人生格言
  motto: 人外有人，天外有天

# about页面配置slot
slots:
  - slot:
      title: 123
      lists:
        - link: xxx
  - slot:
      title: 234
      lists:
